### ISSUE TITLE
Promise Future

### ISSUE THREAD

**Issue by alob-mtc** [alob-mtc/go-future#3]
```go
f = e.NewFuture()

Then

//Register a future event 
f.OnComplete(func (){
  // do something
})


// Then in my go routine for example...I can do

go func(){
  //some long-running process
  if done {
     f.SignalComplete()
  }
}()
```

**Comment by opensaucerer** [comment]
extending even further....futures allow for the passing of parameters given in the form of....

```go
package main

import (
    "fmt"
    gp "https://github.com/alob-mtc/go-promise"
)

func main() {
    // create a new future
    f := gp.NewFuture()
    // register a future event - blocks the main routine until signaled
    f.RegisterComplete(func(data interface{}) {
        fmt.Printf("Future responded with: %s", data.(string))
    })
    // do some long running sorcery
    go func() {
        <-time.After(5 * time.Second)
        // signal the future event
        f.SignalComplete("Hello World")
    }()
}
```

**Comment by alob-mtc** [comment]
Thanks for this cool contribution, I think this future would grow to become its own thing, and we can benefit more by making this feature its stand-alone package.

I have decided to go a different direction with this go-promise implementation which might require that I remove this future implementation.

**Comment by opensaucerer** [comment]
Was actually having thoughts around it being standalone... it's the best move. I'll close the PR since I have moved it over to a new home at [wormhole](https://github.com/opensaucerer/wormhole)
